### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by sv3nnie** [pjotrvp/GymBulkShop#6]
Hello there!

I noticed that this repository doesn't have a README file. As a fellow GitHub user, I highly recommend adding one to your repository. 

A README file serves as a first point of contact for anyone who visits your repository. It provides an introduction to your project, explains what it does, and how one can get started with it. The README file is a great way to communicate important information about your project, such as installation steps, usage instructions, and features. 

Additionally, a README makes it easier for potential contributors to understand what your project is all about. By keeping it up-to-date with information on how to contribute, you'll attract more people who are interested in your work.

Creating a README file doesn't have to be complicated. Simply create a new file called README.md in the root of your repository, and start writing! There are many great resources and templates available online to get you started.

Thank you for considering my suggestion. I look forward to seeing a shiny new README file added to your repository soon!

**Comment by pjotrvp** [comment]
We will be looking into adding a readme in the future of this application, perhaps when the application is fully finished and in production

**Comment by sv3nnie** [comment]
> We will be looking into adding a readme in the future of this application, perhaps when the application is fully finished and in production

Thank you for your response. 

I understand your reasoning for waiting until the application is fully finished and in production before adding a README file, but I do encourage you to reconsider.

Even if the application is not yet fully finished, a README file can provide valuable information and guidance for anyone who may want to use or contribute to the project. Additionally, having a README file early on might encourage more people to get involved in the project, which in turn could accelerate the development process.

If you need any help or guidance on how to create a README file, please let me know. I would be happy to assist you in any way I can.

Thank you for your consideration.
